#!/bin/bash
GITDIR=$(pwd)
if [ -e ~/.vimrc ]
then
    echo ".vimrc detected, moving to .vimrc.bak"
    mv ~/.vimrc ~/.vimrc.bak
fi
echo "symlinking .vimrc to git repo"
ln -s $GITDIR/vimrc ~/.vimrc
git submodule update --init --recursive
